<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Magefox\SSOIntegration\Block\Account\AuthorizationLink
 */
?>
<li class="authorization-link"
    data-mage-init='{
        "magefox.auth0": {
            "clientId": "<?= $block->getAuth0()->getClientId()?>",
            "domain": "<?= $block->getAuth0()->getDomain()?>",
            "redirectUrl": "<?= $block->getAuth0()->getCallbackUrl()?>",
            "section": "<?= $block->getSection()?>"
        }
    }'
>
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <?= $block->escapeHtml($block->getLabel()) ?>
    </a>
</li>