<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Magefox\SSOIntegration\Block\Auth0
 */
?>
<li class="authorization-link"
    data-mage-init='{
        "magefox.auth0": {
            "clientId": "<?= $block->getConfig()->getClientId()?>",
            "domain": "<?= $block->getConfig()->getDomain()?>",
            "state": "<?= $block->getFormKey()?>",
            "logo": "<?= $block->getLogoSrc()?>",
            "redirectUrl": "<?= $block->getConfig()->getCallbackUrl()?>"
        }
    }'
>
    <a href="javascript:void">
        <?= __('Login or Register') ?>
    </a>
</li>